<?php 
$awkwardKarmaNeeded = array(
    "waits.for.anyone" => 0,
    "waits.for.your.reply.only" => 0,
    "i.find.this.unworthy.for.discussion" => 0,
    "i.find.the.subject.unworthy.for.discussion" => 0,
    "i.will.not.reply.and.expect.apology" => 0,
    "i.apologize" => 0,
    "no.problem" => 0,
    "your.comment.inspired.me" => 0,
	"thanks" => 0,
	"youre.welcome" => 0,
    "i.dont.think.the.original.post.has.been.addressed.yet" => 0,
    "i.dont.think.the.original.post.has.been.taken.seriously.yet" => 0,
    "i.dont.think.the.original.post.has.been.treated.respectfully" => 0,
    "guarded.apology" => 0,
    "explanation.why.i.was.angry" => 0,
    "dont.mind.its.ok.lets.move.on" => 0,
    "i.was.being.careless" => 0,
    "i.am.glad.you.said.that.to.me" => 0,
    "its.fine.i.consider.the.case.closed" =>0 ,
    "i.consider.this.comment.definitive.and.consider.any.reply.inappropriate" => 0,
    "interesting.will.write.more.in.a.few.days.time" => 0,
    "i.am.one.of.the.strangest.people.youll.ever.meet" => 0,
    "er.hi.what.kind.of.strange.presentation.is.that" => 0,
    "youre.being.overly.ironic.and.are.violating.the.rules" => 0,
    "awkward" => 0,
    "watch.me.playing.soccer.with.myself.in.this.video" => 0,
	"that.pissed.me.off.but.please.dont.mind" => 0,
	"thanks.but.a.bit.off.topic" => 0,
	"your.post.inspired.me" => 0,
	"your.link.inspired.me" => 0,
	"a.warning.from.one.intellectual.to.another" => 0,
	"i.wont.comment.for.personal.reasons" => 0,
	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => 0
);

$awkwardKarmaRewards = array(
    "waits.for.anyone" => 0,
    "waits.for.your.reply.only" => 0,
    "i.find.this.unworthy.for.discussion" => 0,
    "i.find.the.subject.unworthy.for.discussion" => 0,
    "i.will.not.reply.and.expect.apology" => 0,
    "i.apologize" => 0,
    "no.problem" => 0,
    "your.comment.inspired.me" => 0,
	"thanks" => 0,
	"youre.welcome" => 0,
    "i.dont.think.the.original.post.has.been.addressed.yet" => 0,
    "i.dont.think.the.original.post.has.been.taken.seriously.yet" => 0,
    "i.dont.think.the.original.post.has.been.treated.respectfully" => 0,
    "guarded.apology" => 0,
    "explanation.why.i.was.angry" => 0,
    "dont.mind.its.ok.lets.move.on" => 0,
    "i.was.being.careless" => 0,
    "i.am.glad.you.said.that.to.me" => 0,
    "its.fine.i.consider.the.case.closed" =>0 ,
    "i.consider.this.comment.definitive.and.consider.any.reply.inappropriate" => 0,
    "interesting.will.write.more.in.a.few.days.time" => 0,
    "i.am.one.of.the.strangest.people.youll.ever.meet" => 0,
    "er.hi.what.kind.of.strange.presentation.is.that" => 0,
    "youre.being.overly.ironic.and.are.violating.the.rules" => 0,
    "awkward" => 0,
    "watch.me.playing.soccer.with.myself.in.this.video" => 0,
	"that.pissed.me.off.but.please.dont.mind" => 0,
	"thanks.but.a.bit.off.topic" => 0,
	"your.post.inspired.me" => 0,
	"your.link.inspired.me" => 0,
	"a.warning.from.one.intellectual.to.another" => 0,
	"i.wont.comment.for.personal.reasons" => 0,
	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => 0
);

$tagCategories = array(
    "waits.for.anyone" => "Requests",
    "waits.for.your.reply.only" => "Requests",
	 
	"awkward" => "Awkward",

    "i.find.this.unworthy.for.discussion" => "Outrule",
    "i.find.the.subject.unworthy.for.discussion" => "Outrule",

    "i.will.not.reply.and.expect.apology" => "Anger",
	"that.pissed.me.off.but.please.dont.mind" => "Anger",

    "i.apologize" => "Apology",
    "no.problem" => "Apology",
    "guarded.apology" => "Apology",
    "explanation.why.i.was.angry" => "Apology",
    "dont.mind.its.ok.lets.move.on" => "Apology",
    "i.was.being.careless" => "Apology",
	"its.fine.i.consider.the.case.closed" => "Apology" ,

    "your.comment.inspired.me" => "Praise",
	"thanks" => "Praise",
	"youre.welcome" => "Praise",
    "i.am.glad.you.said.that.to.me" => "Praise",
	"your.post.inspired.me" => "Praise",
	"your.link.inspired.me" => "Praise",

    "i.dont.think.the.original.post.has.been.addressed.yet" => "Meta",
    "i.dont.think.the.original.post.has.been.taken.seriously.yet" => "Meta",
    "i.dont.think.the.original.post.has.been.treated.respectfully" => "Meta",
    "i.consider.this.comment.definitive.and.consider.any.reply.inappropriate" => "Meta",
    "youre.being.overly.ironic.and.are.violating.the.rules" => "Meta",
	"thanks.but.a.bit.off.topic" => "Meta",
	"a.warning.from.one.intellectual.to.another" => "Meta",

    "interesting.will.write.more.in.a.few.days.time" => "Patience",

	"i.wont.comment.for.personal.reasons" => "Personal",

    "watch.me.playing.soccer.with.myself.in.this.video" => "Funny",
    "i.am.one.of.the.strangest.people.youll.ever.meet" => "Funny",
    "er.hi.what.kind.of.strange.presentation.is.that" => "Funny",

	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => "Courage"
);

$relationalKarmaNeeded = array(
    "waits.for.your.reply.only" => 0,
    "i.will.not.reply.and.expect.apology" => 0,
    "i.apologize" => 0,
    "no.problem" => 0,
    "your.comment.inspired.me" => 0,
	"thanks" => 0,
	"youre.welcome" => 0,
    "guarded.apology" => 0,
    "explanation.why.i.was.angry" => 0,
    "dont.mind.its.ok.lets.move.on" => 0,
    "i.was.being.careless" => 0,
    "i.am.glad.you.said.that.to.me" => 0,
    "its.fine.i.consider.the.case.closed" =>0 ,
    "interesting.will.write.more.in.a.few.days.time" => 0,
    "i.am.one.of.the.strangest.people.youll.ever.meet" => 0,
    "er.hi.what.kind.of.strange.presentation.is.that" => 0,
    "awkward" => 0,
	"that.pissed.me.off.but.please.dont.mind" => 0,
	"thanks.but.a.bit.off.topic" => 0,
	"your.post.inspired.me" => 0,
	"your.link.inspired.me" => 0,
	"a.warning.from.one.intellectual.to.another" => 0,
	"i.wont.comment.for.personal.reasons" => 0,
	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => 0
);
/*
Allowed values:

mayNotStandAlone
mustStandAlone
noStandAloneRule
takenCareOfElsewhere
*/
$mustBeStandAloneTags = array(
	"waits.for.anyone" => "mayNotStandAlone",
    "waits.for.your.reply.only" => "mayNotStandAlone",
    "i.find.this.unworthy.for.discussion" => "noStandAloneRule",
    "i.find.the.subject.unworthy.for.discussion" => "noStandAloneRule",
    "i.will.not.reply.and.expect.apology" => "mustStandAlone",
    "i.apologize" => "mustStandAlone",
    "no.problem" => "mustStandAlone",
    "your.comment.inspired.me" => "takenCareOfElsewhere",
	"thanks" => "noStandAloneRule",
	"youre.welcome" => "noStandAloneRule",
    "i.dont.think.the.original.post.has.been.addressed.yet" => "noStandAloneRule",
    "i.dont.think.the.original.post.has.been.taken.seriously.yet" => "noStandAloneRule",
    "i.dont.think.the.original.post.has.been.treated.respectfully" => "noStandAloneRule",
    "guarded.apology" => "mayNotStandAlone",
    "explanation.why.i.was.angry" => "mayNotStandAlone",
    "dont.mind.its.ok.lets.move.on" => "noStandAloneRule",
    "i.was.being.careless" => "noStandAloneRule",
    "i.am.glad.you.said.that.to.me" => "noStandAloneRule",
    "its.fine.i.consider.the.case.closed" => "noStandAloneRule" ,
    "i.consider.this.comment.definitive.and.consider.any.reply.inappropriate" => "mayNotStandAlone",
    "interesting.will.write.more.in.a.few.days.time" => "noStandAloneRule",
    "i.am.one.of.the.strangest.people.youll.ever.meet" => "noStandAloneRule",
    "er.hi.what.kind.of.strange.presentation.is.that" => "noStandAloneRule",
    "youre.being.overly.ironic.and.are.violating.the.rules" => "noStandAloneRule",
    "awkward" => "takenCareOfElsewhere",
    "watch.me.playing.soccer.with.myself.in.this.video" => "noStandAloneRule",
	"that.pissed.me.off.but.please.dont.mind" => "takenCareOfElsewhere",
	"thanks.but.a.bit.off.topic" => "noStandAloneRule",
	"your.post.inspired.me" => "noStandAloneRule",
	"your.link.inspired.me" => "noStandAloneRule",
	"a.warning.from.one.intellectual.to.another" => "mayNotStandAlone",
	"i.wont.comment.for.personal.reasons" => "mayNotStandAlone",
	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => "mayNotStandAlone"
);

$intuitiveTagNames = array(
	"waits.for.anyone" => "Waits for anyone...",
    "waits.for.your.reply.only" => "Waits for your reply only...",
    "i.find.this.unworthy.for.discussion" => "I find this unworthy for discussion",
    "i.find.the.subject.unworthy.for.discussion" => "I find the subject unworthy for discussion",
    "i.will.not.reply.and.expect.apology" => "I will not reply and expect an apology",
    "i.apologize" => "I apologize",
    "no.problem" => "No problem",
    "your.comment.inspired.me" => "Your comment inspired me...",
	"thanks" => "Thanks!",
	"youre.welcome" => "You're welcome",
    "i.dont.think.the.original.post.has.been.addressed.yet" => "I don't think the original post has been addressed yet",
    "i.dont.think.the.original.post.has.been.taken.seriously.yet" => "I don't think the original post has been taken seriously yet",
    "i.dont.think.the.original.post.has.been.treated.respectfully" => "I don't think the original post has been treated respectfully",
    "guarded.apology" => "Guarded apology",
    "explanation.why.i.was.angry" => "Explanation why I was angry",
    "dont.mind.its.ok.lets.move.on" => "Don't mind. It's ok. Let's move on...",
    "i.was.being.careless" => "I was being careless",
    "i.am.glad.you.said.that.to.me" => "I'm glad you said that to me",
    "its.fine.i.consider.the.case.closed" => "It's fine. I consider the case closed" ,
    "i.consider.this.comment.definitive.and.consider.any.reply.inappropriate" => "I consider this comment definitive and consider any reply inappropriate",
    "interesting.will.write.more.in.a.few.days.time" => "Interesting. Will write more in a few days time",
    "i.am.one.of.the.strangest.people.youll.ever.meet" => "I am one of the strangest people you'll ever meet",
    "er.hi.what.kind.of.strange.presentation.is.that" => "Er. What kind of strange presentation is that...",
    "youre.being.overly.ironic.and.are.violating.the.rules" => "You're being overly ironic and are violating the rules",
    "awkward" => "The famous awkward tag",
    "watch.me.playing.soccer.with.myself.in.this.video" => "Watch me playing soccer with myself in this video",
	"that.pissed.me.off.but.please.dont.mind" => "That pissed me off, but please don't mind",
	"thanks.but.a.bit.off.topic" => "Thanks. But a bit off-topic...",
	"your.post.inspired.me" => "Your post inspired me",
	"your.link.inspired.me" => "Your link inspired me",
	"a.warning.from.one.intellectual.to.another" => "A warning from one intellectual to another",
	"i.wont.comment.for.personal.reasons" => "I won't comment for personal reasons",
	"a.warm.welcome.to.my.world.without.a.naive.invitation.to.be.my.friend" => "A warm welcome to my world, without a naive invitation to be my friend"
);

?>
